name: Update Steam Intel Page

on:
  schedule:
    - cron: '0 */6 * * *' # 每12小时运行
  workflow_dispatch:      # 允许手动点按钮运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install feedparser

      - name: Run Update Script
        run: python steam_intel.py 

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Auto Update News" || echo "No changes"
          git push
